title: Khushi Sharma
logo: assets/img/khushi.png
description: Result-driven aspiring AI Engineer with a strong passion for learning and applying skills in NLP, ML, and Data Science. Skilled in multilingual Named Entity Recognition, data analysis, and working with large language models. Proficient in Python, Java, and frameworks like PyTorch and Spring. Excellent communicator and problem solver, dedicated to delivering technological solutions to complex problems. Aiming to continually enhance my skills in Machine Learning and NLP to make a tangible real-world impact through their application.
#show_downloads: true
theme: jekyll-theme-minimal
