title: Khushi Sharma
logo: assets/img/khushi.png
description: Result-driven innovative AI Engineer with a passion for Generative AI and Data Science. Experienced in developing advanced AI solutions and optimizing user experiences. Adept at creating engaging interactions and delivering tangible business impacts. Seeking to leverage my skills to enhance customer, employee, and agent experiences through cutting-edge AI technologies.
#show_downloads: true
theme: jekyll-theme-minimal
